#Application properties
server:
  port: 8081


#AWS properties
cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      accessKey: ${{AWS_ACCESSKEY}}
      secretKey: ${{AWS_SECRETKEY}}

application:
  bucket:
    name: cloudsavemanager

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
