server:
  port: 8081
cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      accessKey: AKIAYQ6HBCMECTTAC6US
      secretKey: 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
      kms: 9755f95f-27bd-45f7-9985-728115eacca4
application:
  bucket:
    name: cloudsavemanager
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
