name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: pull the docker image
      run: sudo docker pull moeztahir96/cloudsavemanagerbackend:latest
    - name: Delete old docker container
      run: docker rm -f cloudsavemanager-container || true
    - name: Run docker container
      run: sudo docker run -d -p 8081:8081 --name cloudsavemanager-container moeztahir96/cloudsavemanager
